name: buildtex

on:
  push:
    branches: main
    paths: [docs/**]
  pull_request:
    branches: main
    paths: [docs/**]

permissions:
  contents: write

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed LaTeX files
        id: latex-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- docs/**/*.tex | xargs)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
      - uses: xu-cheng/texlive-action@v2
        name: Compile LaTeX Files
        with:
          scheme: full
          texlive_version: 2024
          run: |
            apt update
            apt install -y make
            cd docs
            for file in ${{ env.CHANGED_FILES }}; do 
              dir=$(dirname "$file" | cut -d'/' -f2-)
              make "$dir/$(basename "$file" .tex).pdf" 
            done
      - name: Commit and push PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add/Update PDFs for changed LaTeX files: ${{ env.CHANGED_FILES }}'
          file_pattern: 'docs/*.pdf'
          branch: main
