name: buildtex

on:
  push:
    branches: main
    paths: [docs/**]
  pull_request:
    branches: main
    paths: [docs/**]

permissions:
  contents: write

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the previous commit
        id: previous-commit
        run: echo "::set-output name=previous_commit::$(git rev-parse HEAD~1)"
      - name: Get changed LaTeX files
        id: latex-files
        run: |
          PREV_COMMIT=${{ github.event.before || steps.previous-commit.outputs.previous_commit }}
          CHANGED_FILES=$(git diff --name-only $PREV_COMMIT ${{ github.sha }} -- docs/*.tex)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
      - name: Install dependencies and compile LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          cd docs
          for file in ${{ env.CHANGED_FILES }}; do
            make $(basename "$file" .tex).pdf
          done
      - name: Commit and push PDFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add/Update PDFs for changed LaTeX files: ${{ env.CHANGED_FILES }}'
          file_pattern: 'docs/*.pdf'
          branch: main
